import * as _166 from "./abci/types";
import * as _167 from "./crypto/keys";
import * as _168 from "./crypto/proof";
import * as _169 from "./libs/bits/types";
import * as _170 from "./p2p/types";
import * as _171 from "./types/block";
import * as _172 from "./types/evidence";
import * as _173 from "./types/params";
import * as _174 from "./types/types";
import * as _175 from "./types/validator";
import * as _176 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _166.CheckTxType;
        checkTxTypeToJSON(object: _166.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _166.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _166.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _166.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _166.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _166.EvidenceType;
        evidenceTypeToJSON(object: _166.EvidenceType): string;
        CheckTxType: typeof _166.CheckTxType;
        CheckTxTypeSDKType: typeof _166.CheckTxType;
        CheckTxTypeAmino: typeof _166.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _166.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _166.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _166.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _166.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _166.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _166.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _166.EvidenceType;
        EvidenceTypeSDKType: typeof _166.EvidenceType;
        EvidenceTypeAmino: typeof _166.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _166.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Request;
            fromPartial(object: Partial<_166.Request>): _166.Request;
            fromAmino(object: _166.RequestAmino): _166.Request;
            toAmino(message: _166.Request): _166.RequestAmino;
            fromAminoMsg(object: _166.RequestAminoMsg): _166.Request;
            fromProtoMsg(message: _166.RequestProtoMsg): _166.Request;
            toProto(message: _166.Request): Uint8Array;
            toProtoMsg(message: _166.Request): _166.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _166.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestEcho;
            fromPartial(object: Partial<_166.RequestEcho>): _166.RequestEcho;
            fromAmino(object: _166.RequestEchoAmino): _166.RequestEcho;
            toAmino(message: _166.RequestEcho): _166.RequestEchoAmino;
            fromAminoMsg(object: _166.RequestEchoAminoMsg): _166.RequestEcho;
            fromProtoMsg(message: _166.RequestEchoProtoMsg): _166.RequestEcho;
            toProto(message: _166.RequestEcho): Uint8Array;
            toProtoMsg(message: _166.RequestEcho): _166.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _166.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestFlush;
            fromPartial(_: Partial<_166.RequestFlush>): _166.RequestFlush;
            fromAmino(_: _166.RequestFlushAmino): _166.RequestFlush;
            toAmino(_: _166.RequestFlush): _166.RequestFlushAmino;
            fromAminoMsg(object: _166.RequestFlushAminoMsg): _166.RequestFlush;
            fromProtoMsg(message: _166.RequestFlushProtoMsg): _166.RequestFlush;
            toProto(message: _166.RequestFlush): Uint8Array;
            toProtoMsg(message: _166.RequestFlush): _166.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _166.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestInfo;
            fromPartial(object: Partial<_166.RequestInfo>): _166.RequestInfo;
            fromAmino(object: _166.RequestInfoAmino): _166.RequestInfo;
            toAmino(message: _166.RequestInfo): _166.RequestInfoAmino;
            fromAminoMsg(object: _166.RequestInfoAminoMsg): _166.RequestInfo;
            fromProtoMsg(message: _166.RequestInfoProtoMsg): _166.RequestInfo;
            toProto(message: _166.RequestInfo): Uint8Array;
            toProtoMsg(message: _166.RequestInfo): _166.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _166.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestSetOption;
            fromPartial(object: Partial<_166.RequestSetOption>): _166.RequestSetOption;
            fromAmino(object: _166.RequestSetOptionAmino): _166.RequestSetOption;
            toAmino(message: _166.RequestSetOption): _166.RequestSetOptionAmino;
            fromAminoMsg(object: _166.RequestSetOptionAminoMsg): _166.RequestSetOption;
            fromProtoMsg(message: _166.RequestSetOptionProtoMsg): _166.RequestSetOption;
            toProto(message: _166.RequestSetOption): Uint8Array;
            toProtoMsg(message: _166.RequestSetOption): _166.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _166.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestInitChain;
            fromPartial(object: Partial<_166.RequestInitChain>): _166.RequestInitChain;
            fromAmino(object: _166.RequestInitChainAmino): _166.RequestInitChain;
            toAmino(message: _166.RequestInitChain): _166.RequestInitChainAmino;
            fromAminoMsg(object: _166.RequestInitChainAminoMsg): _166.RequestInitChain;
            fromProtoMsg(message: _166.RequestInitChainProtoMsg): _166.RequestInitChain;
            toProto(message: _166.RequestInitChain): Uint8Array;
            toProtoMsg(message: _166.RequestInitChain): _166.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _166.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestQuery;
            fromPartial(object: Partial<_166.RequestQuery>): _166.RequestQuery;
            fromAmino(object: _166.RequestQueryAmino): _166.RequestQuery;
            toAmino(message: _166.RequestQuery): _166.RequestQueryAmino;
            fromAminoMsg(object: _166.RequestQueryAminoMsg): _166.RequestQuery;
            fromProtoMsg(message: _166.RequestQueryProtoMsg): _166.RequestQuery;
            toProto(message: _166.RequestQuery): Uint8Array;
            toProtoMsg(message: _166.RequestQuery): _166.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _166.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestBeginBlock;
            fromPartial(object: Partial<_166.RequestBeginBlock>): _166.RequestBeginBlock;
            fromAmino(object: _166.RequestBeginBlockAmino): _166.RequestBeginBlock;
            toAmino(message: _166.RequestBeginBlock): _166.RequestBeginBlockAmino;
            fromAminoMsg(object: _166.RequestBeginBlockAminoMsg): _166.RequestBeginBlock;
            fromProtoMsg(message: _166.RequestBeginBlockProtoMsg): _166.RequestBeginBlock;
            toProto(message: _166.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _166.RequestBeginBlock): _166.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _166.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestCheckTx;
            fromPartial(object: Partial<_166.RequestCheckTx>): _166.RequestCheckTx;
            fromAmino(object: _166.RequestCheckTxAmino): _166.RequestCheckTx;
            toAmino(message: _166.RequestCheckTx): _166.RequestCheckTxAmino;
            fromAminoMsg(object: _166.RequestCheckTxAminoMsg): _166.RequestCheckTx;
            fromProtoMsg(message: _166.RequestCheckTxProtoMsg): _166.RequestCheckTx;
            toProto(message: _166.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _166.RequestCheckTx): _166.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _166.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestDeliverTx;
            fromPartial(object: Partial<_166.RequestDeliverTx>): _166.RequestDeliverTx;
            fromAmino(object: _166.RequestDeliverTxAmino): _166.RequestDeliverTx;
            toAmino(message: _166.RequestDeliverTx): _166.RequestDeliverTxAmino;
            fromAminoMsg(object: _166.RequestDeliverTxAminoMsg): _166.RequestDeliverTx;
            fromProtoMsg(message: _166.RequestDeliverTxProtoMsg): _166.RequestDeliverTx;
            toProto(message: _166.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _166.RequestDeliverTx): _166.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _166.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestEndBlock;
            fromPartial(object: Partial<_166.RequestEndBlock>): _166.RequestEndBlock;
            fromAmino(object: _166.RequestEndBlockAmino): _166.RequestEndBlock;
            toAmino(message: _166.RequestEndBlock): _166.RequestEndBlockAmino;
            fromAminoMsg(object: _166.RequestEndBlockAminoMsg): _166.RequestEndBlock;
            fromProtoMsg(message: _166.RequestEndBlockProtoMsg): _166.RequestEndBlock;
            toProto(message: _166.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _166.RequestEndBlock): _166.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _166.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestCommit;
            fromPartial(_: Partial<_166.RequestCommit>): _166.RequestCommit;
            fromAmino(_: _166.RequestCommitAmino): _166.RequestCommit;
            toAmino(_: _166.RequestCommit): _166.RequestCommitAmino;
            fromAminoMsg(object: _166.RequestCommitAminoMsg): _166.RequestCommit;
            fromProtoMsg(message: _166.RequestCommitProtoMsg): _166.RequestCommit;
            toProto(message: _166.RequestCommit): Uint8Array;
            toProtoMsg(message: _166.RequestCommit): _166.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _166.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestListSnapshots;
            fromPartial(_: Partial<_166.RequestListSnapshots>): _166.RequestListSnapshots;
            fromAmino(_: _166.RequestListSnapshotsAmino): _166.RequestListSnapshots;
            toAmino(_: _166.RequestListSnapshots): _166.RequestListSnapshotsAmino;
            fromAminoMsg(object: _166.RequestListSnapshotsAminoMsg): _166.RequestListSnapshots;
            fromProtoMsg(message: _166.RequestListSnapshotsProtoMsg): _166.RequestListSnapshots;
            toProto(message: _166.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _166.RequestListSnapshots): _166.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _166.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestOfferSnapshot;
            fromPartial(object: Partial<_166.RequestOfferSnapshot>): _166.RequestOfferSnapshot;
            fromAmino(object: _166.RequestOfferSnapshotAmino): _166.RequestOfferSnapshot;
            toAmino(message: _166.RequestOfferSnapshot): _166.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _166.RequestOfferSnapshotAminoMsg): _166.RequestOfferSnapshot;
            fromProtoMsg(message: _166.RequestOfferSnapshotProtoMsg): _166.RequestOfferSnapshot;
            toProto(message: _166.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _166.RequestOfferSnapshot): _166.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _166.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_166.RequestLoadSnapshotChunk>): _166.RequestLoadSnapshotChunk;
            fromAmino(object: _166.RequestLoadSnapshotChunkAmino): _166.RequestLoadSnapshotChunk;
            toAmino(message: _166.RequestLoadSnapshotChunk): _166.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _166.RequestLoadSnapshotChunkAminoMsg): _166.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _166.RequestLoadSnapshotChunkProtoMsg): _166.RequestLoadSnapshotChunk;
            toProto(message: _166.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _166.RequestLoadSnapshotChunk): _166.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _166.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_166.RequestApplySnapshotChunk>): _166.RequestApplySnapshotChunk;
            fromAmino(object: _166.RequestApplySnapshotChunkAmino): _166.RequestApplySnapshotChunk;
            toAmino(message: _166.RequestApplySnapshotChunk): _166.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _166.RequestApplySnapshotChunkAminoMsg): _166.RequestApplySnapshotChunk;
            fromProtoMsg(message: _166.RequestApplySnapshotChunkProtoMsg): _166.RequestApplySnapshotChunk;
            toProto(message: _166.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _166.RequestApplySnapshotChunk): _166.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _166.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Response;
            fromPartial(object: Partial<_166.Response>): _166.Response;
            fromAmino(object: _166.ResponseAmino): _166.Response;
            toAmino(message: _166.Response): _166.ResponseAmino;
            fromAminoMsg(object: _166.ResponseAminoMsg): _166.Response;
            fromProtoMsg(message: _166.ResponseProtoMsg): _166.Response;
            toProto(message: _166.Response): Uint8Array;
            toProtoMsg(message: _166.Response): _166.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _166.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseException;
            fromPartial(object: Partial<_166.ResponseException>): _166.ResponseException;
            fromAmino(object: _166.ResponseExceptionAmino): _166.ResponseException;
            toAmino(message: _166.ResponseException): _166.ResponseExceptionAmino;
            fromAminoMsg(object: _166.ResponseExceptionAminoMsg): _166.ResponseException;
            fromProtoMsg(message: _166.ResponseExceptionProtoMsg): _166.ResponseException;
            toProto(message: _166.ResponseException): Uint8Array;
            toProtoMsg(message: _166.ResponseException): _166.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _166.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseEcho;
            fromPartial(object: Partial<_166.ResponseEcho>): _166.ResponseEcho;
            fromAmino(object: _166.ResponseEchoAmino): _166.ResponseEcho;
            toAmino(message: _166.ResponseEcho): _166.ResponseEchoAmino;
            fromAminoMsg(object: _166.ResponseEchoAminoMsg): _166.ResponseEcho;
            fromProtoMsg(message: _166.ResponseEchoProtoMsg): _166.ResponseEcho;
            toProto(message: _166.ResponseEcho): Uint8Array;
            toProtoMsg(message: _166.ResponseEcho): _166.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _166.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseFlush;
            fromPartial(_: Partial<_166.ResponseFlush>): _166.ResponseFlush;
            fromAmino(_: _166.ResponseFlushAmino): _166.ResponseFlush;
            toAmino(_: _166.ResponseFlush): _166.ResponseFlushAmino;
            fromAminoMsg(object: _166.ResponseFlushAminoMsg): _166.ResponseFlush;
            fromProtoMsg(message: _166.ResponseFlushProtoMsg): _166.ResponseFlush;
            toProto(message: _166.ResponseFlush): Uint8Array;
            toProtoMsg(message: _166.ResponseFlush): _166.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _166.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseInfo;
            fromPartial(object: Partial<_166.ResponseInfo>): _166.ResponseInfo;
            fromAmino(object: _166.ResponseInfoAmino): _166.ResponseInfo;
            toAmino(message: _166.ResponseInfo): _166.ResponseInfoAmino;
            fromAminoMsg(object: _166.ResponseInfoAminoMsg): _166.ResponseInfo;
            fromProtoMsg(message: _166.ResponseInfoProtoMsg): _166.ResponseInfo;
            toProto(message: _166.ResponseInfo): Uint8Array;
            toProtoMsg(message: _166.ResponseInfo): _166.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _166.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseSetOption;
            fromPartial(object: Partial<_166.ResponseSetOption>): _166.ResponseSetOption;
            fromAmino(object: _166.ResponseSetOptionAmino): _166.ResponseSetOption;
            toAmino(message: _166.ResponseSetOption): _166.ResponseSetOptionAmino;
            fromAminoMsg(object: _166.ResponseSetOptionAminoMsg): _166.ResponseSetOption;
            fromProtoMsg(message: _166.ResponseSetOptionProtoMsg): _166.ResponseSetOption;
            toProto(message: _166.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _166.ResponseSetOption): _166.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _166.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseInitChain;
            fromPartial(object: Partial<_166.ResponseInitChain>): _166.ResponseInitChain;
            fromAmino(object: _166.ResponseInitChainAmino): _166.ResponseInitChain;
            toAmino(message: _166.ResponseInitChain): _166.ResponseInitChainAmino;
            fromAminoMsg(object: _166.ResponseInitChainAminoMsg): _166.ResponseInitChain;
            fromProtoMsg(message: _166.ResponseInitChainProtoMsg): _166.ResponseInitChain;
            toProto(message: _166.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _166.ResponseInitChain): _166.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _166.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseQuery;
            fromPartial(object: Partial<_166.ResponseQuery>): _166.ResponseQuery;
            fromAmino(object: _166.ResponseQueryAmino): _166.ResponseQuery;
            toAmino(message: _166.ResponseQuery): _166.ResponseQueryAmino;
            fromAminoMsg(object: _166.ResponseQueryAminoMsg): _166.ResponseQuery;
            fromProtoMsg(message: _166.ResponseQueryProtoMsg): _166.ResponseQuery;
            toProto(message: _166.ResponseQuery): Uint8Array;
            toProtoMsg(message: _166.ResponseQuery): _166.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _166.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseBeginBlock;
            fromPartial(object: Partial<_166.ResponseBeginBlock>): _166.ResponseBeginBlock;
            fromAmino(object: _166.ResponseBeginBlockAmino): _166.ResponseBeginBlock;
            toAmino(message: _166.ResponseBeginBlock): _166.ResponseBeginBlockAmino;
            fromAminoMsg(object: _166.ResponseBeginBlockAminoMsg): _166.ResponseBeginBlock;
            fromProtoMsg(message: _166.ResponseBeginBlockProtoMsg): _166.ResponseBeginBlock;
            toProto(message: _166.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _166.ResponseBeginBlock): _166.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _166.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseCheckTx;
            fromPartial(object: Partial<_166.ResponseCheckTx>): _166.ResponseCheckTx;
            fromAmino(object: _166.ResponseCheckTxAmino): _166.ResponseCheckTx;
            toAmino(message: _166.ResponseCheckTx): _166.ResponseCheckTxAmino;
            fromAminoMsg(object: _166.ResponseCheckTxAminoMsg): _166.ResponseCheckTx;
            fromProtoMsg(message: _166.ResponseCheckTxProtoMsg): _166.ResponseCheckTx;
            toProto(message: _166.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _166.ResponseCheckTx): _166.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _166.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseDeliverTx;
            fromPartial(object: Partial<_166.ResponseDeliverTx>): _166.ResponseDeliverTx;
            fromAmino(object: _166.ResponseDeliverTxAmino): _166.ResponseDeliverTx;
            toAmino(message: _166.ResponseDeliverTx): _166.ResponseDeliverTxAmino;
            fromAminoMsg(object: _166.ResponseDeliverTxAminoMsg): _166.ResponseDeliverTx;
            fromProtoMsg(message: _166.ResponseDeliverTxProtoMsg): _166.ResponseDeliverTx;
            toProto(message: _166.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _166.ResponseDeliverTx): _166.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _166.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseEndBlock;
            fromPartial(object: Partial<_166.ResponseEndBlock>): _166.ResponseEndBlock;
            fromAmino(object: _166.ResponseEndBlockAmino): _166.ResponseEndBlock;
            toAmino(message: _166.ResponseEndBlock): _166.ResponseEndBlockAmino;
            fromAminoMsg(object: _166.ResponseEndBlockAminoMsg): _166.ResponseEndBlock;
            fromProtoMsg(message: _166.ResponseEndBlockProtoMsg): _166.ResponseEndBlock;
            toProto(message: _166.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _166.ResponseEndBlock): _166.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _166.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseCommit;
            fromPartial(object: Partial<_166.ResponseCommit>): _166.ResponseCommit;
            fromAmino(object: _166.ResponseCommitAmino): _166.ResponseCommit;
            toAmino(message: _166.ResponseCommit): _166.ResponseCommitAmino;
            fromAminoMsg(object: _166.ResponseCommitAminoMsg): _166.ResponseCommit;
            fromProtoMsg(message: _166.ResponseCommitProtoMsg): _166.ResponseCommit;
            toProto(message: _166.ResponseCommit): Uint8Array;
            toProtoMsg(message: _166.ResponseCommit): _166.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _166.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseListSnapshots;
            fromPartial(object: Partial<_166.ResponseListSnapshots>): _166.ResponseListSnapshots;
            fromAmino(object: _166.ResponseListSnapshotsAmino): _166.ResponseListSnapshots;
            toAmino(message: _166.ResponseListSnapshots): _166.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _166.ResponseListSnapshotsAminoMsg): _166.ResponseListSnapshots;
            fromProtoMsg(message: _166.ResponseListSnapshotsProtoMsg): _166.ResponseListSnapshots;
            toProto(message: _166.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _166.ResponseListSnapshots): _166.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _166.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseOfferSnapshot;
            fromPartial(object: Partial<_166.ResponseOfferSnapshot>): _166.ResponseOfferSnapshot;
            fromAmino(object: _166.ResponseOfferSnapshotAmino): _166.ResponseOfferSnapshot;
            toAmino(message: _166.ResponseOfferSnapshot): _166.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _166.ResponseOfferSnapshotAminoMsg): _166.ResponseOfferSnapshot;
            fromProtoMsg(message: _166.ResponseOfferSnapshotProtoMsg): _166.ResponseOfferSnapshot;
            toProto(message: _166.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _166.ResponseOfferSnapshot): _166.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _166.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_166.ResponseLoadSnapshotChunk>): _166.ResponseLoadSnapshotChunk;
            fromAmino(object: _166.ResponseLoadSnapshotChunkAmino): _166.ResponseLoadSnapshotChunk;
            toAmino(message: _166.ResponseLoadSnapshotChunk): _166.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _166.ResponseLoadSnapshotChunkAminoMsg): _166.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _166.ResponseLoadSnapshotChunkProtoMsg): _166.ResponseLoadSnapshotChunk;
            toProto(message: _166.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _166.ResponseLoadSnapshotChunk): _166.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _166.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_166.ResponseApplySnapshotChunk>): _166.ResponseApplySnapshotChunk;
            fromAmino(object: _166.ResponseApplySnapshotChunkAmino): _166.ResponseApplySnapshotChunk;
            toAmino(message: _166.ResponseApplySnapshotChunk): _166.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _166.ResponseApplySnapshotChunkAminoMsg): _166.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _166.ResponseApplySnapshotChunkProtoMsg): _166.ResponseApplySnapshotChunk;
            toProto(message: _166.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _166.ResponseApplySnapshotChunk): _166.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _166.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ConsensusParams;
            fromPartial(object: Partial<_166.ConsensusParams>): _166.ConsensusParams;
            fromAmino(object: _166.ConsensusParamsAmino): _166.ConsensusParams;
            toAmino(message: _166.ConsensusParams): _166.ConsensusParamsAmino;
            fromAminoMsg(object: _166.ConsensusParamsAminoMsg): _166.ConsensusParams;
            fromProtoMsg(message: _166.ConsensusParamsProtoMsg): _166.ConsensusParams;
            toProto(message: _166.ConsensusParams): Uint8Array;
            toProtoMsg(message: _166.ConsensusParams): _166.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _166.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.BlockParams;
            fromPartial(object: Partial<_166.BlockParams>): _166.BlockParams;
            fromAmino(object: _166.BlockParamsAmino): _166.BlockParams;
            toAmino(message: _166.BlockParams): _166.BlockParamsAmino;
            fromAminoMsg(object: _166.BlockParamsAminoMsg): _166.BlockParams;
            fromProtoMsg(message: _166.BlockParamsProtoMsg): _166.BlockParams;
            toProto(message: _166.BlockParams): Uint8Array;
            toProtoMsg(message: _166.BlockParams): _166.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _166.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.LastCommitInfo;
            fromPartial(object: Partial<_166.LastCommitInfo>): _166.LastCommitInfo;
            fromAmino(object: _166.LastCommitInfoAmino): _166.LastCommitInfo;
            toAmino(message: _166.LastCommitInfo): _166.LastCommitInfoAmino;
            fromAminoMsg(object: _166.LastCommitInfoAminoMsg): _166.LastCommitInfo;
            fromProtoMsg(message: _166.LastCommitInfoProtoMsg): _166.LastCommitInfo;
            toProto(message: _166.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _166.LastCommitInfo): _166.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _166.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Event;
            fromPartial(object: Partial<_166.Event>): _166.Event;
            fromAmino(object: _166.EventAmino): _166.Event;
            toAmino(message: _166.Event): _166.EventAmino;
            fromAminoMsg(object: _166.EventAminoMsg): _166.Event;
            fromProtoMsg(message: _166.EventProtoMsg): _166.Event;
            toProto(message: _166.Event): Uint8Array;
            toProtoMsg(message: _166.Event): _166.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _166.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.EventAttribute;
            fromPartial(object: Partial<_166.EventAttribute>): _166.EventAttribute;
            fromAmino(object: _166.EventAttributeAmino): _166.EventAttribute;
            toAmino(message: _166.EventAttribute): _166.EventAttributeAmino;
            fromAminoMsg(object: _166.EventAttributeAminoMsg): _166.EventAttribute;
            fromProtoMsg(message: _166.EventAttributeProtoMsg): _166.EventAttribute;
            toProto(message: _166.EventAttribute): Uint8Array;
            toProtoMsg(message: _166.EventAttribute): _166.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _166.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.TxResult;
            fromPartial(object: Partial<_166.TxResult>): _166.TxResult;
            fromAmino(object: _166.TxResultAmino): _166.TxResult;
            toAmino(message: _166.TxResult): _166.TxResultAmino;
            fromAminoMsg(object: _166.TxResultAminoMsg): _166.TxResult;
            fromProtoMsg(message: _166.TxResultProtoMsg): _166.TxResult;
            toProto(message: _166.TxResult): Uint8Array;
            toProtoMsg(message: _166.TxResult): _166.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _166.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Validator;
            fromPartial(object: Partial<_166.Validator>): _166.Validator;
            fromAmino(object: _166.ValidatorAmino): _166.Validator;
            toAmino(message: _166.Validator): _166.ValidatorAmino;
            fromAminoMsg(object: _166.ValidatorAminoMsg): _166.Validator;
            fromProtoMsg(message: _166.ValidatorProtoMsg): _166.Validator;
            toProto(message: _166.Validator): Uint8Array;
            toProtoMsg(message: _166.Validator): _166.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _166.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.ValidatorUpdate;
            fromPartial(object: Partial<_166.ValidatorUpdate>): _166.ValidatorUpdate;
            fromAmino(object: _166.ValidatorUpdateAmino): _166.ValidatorUpdate;
            toAmino(message: _166.ValidatorUpdate): _166.ValidatorUpdateAmino;
            fromAminoMsg(object: _166.ValidatorUpdateAminoMsg): _166.ValidatorUpdate;
            fromProtoMsg(message: _166.ValidatorUpdateProtoMsg): _166.ValidatorUpdate;
            toProto(message: _166.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _166.ValidatorUpdate): _166.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _166.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.VoteInfo;
            fromPartial(object: Partial<_166.VoteInfo>): _166.VoteInfo;
            fromAmino(object: _166.VoteInfoAmino): _166.VoteInfo;
            toAmino(message: _166.VoteInfo): _166.VoteInfoAmino;
            fromAminoMsg(object: _166.VoteInfoAminoMsg): _166.VoteInfo;
            fromProtoMsg(message: _166.VoteInfoProtoMsg): _166.VoteInfo;
            toProto(message: _166.VoteInfo): Uint8Array;
            toProtoMsg(message: _166.VoteInfo): _166.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _166.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Evidence;
            fromPartial(object: Partial<_166.Evidence>): _166.Evidence;
            fromAmino(object: _166.EvidenceAmino): _166.Evidence;
            toAmino(message: _166.Evidence): _166.EvidenceAmino;
            fromAminoMsg(object: _166.EvidenceAminoMsg): _166.Evidence;
            fromProtoMsg(message: _166.EvidenceProtoMsg): _166.Evidence;
            toProto(message: _166.Evidence): Uint8Array;
            toProtoMsg(message: _166.Evidence): _166.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _166.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _166.Snapshot;
            fromPartial(object: Partial<_166.Snapshot>): _166.Snapshot;
            fromAmino(object: _166.SnapshotAmino): _166.Snapshot;
            toAmino(message: _166.Snapshot): _166.SnapshotAmino;
            fromAminoMsg(object: _166.SnapshotAminoMsg): _166.Snapshot;
            fromProtoMsg(message: _166.SnapshotProtoMsg): _166.Snapshot;
            toProto(message: _166.Snapshot): Uint8Array;
            toProtoMsg(message: _166.Snapshot): _166.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _168.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _168.Proof;
            fromPartial(object: Partial<_168.Proof>): _168.Proof;
            fromAmino(object: _168.ProofAmino): _168.Proof;
            toAmino(message: _168.Proof): _168.ProofAmino;
            fromAminoMsg(object: _168.ProofAminoMsg): _168.Proof;
            fromProtoMsg(message: _168.ProofProtoMsg): _168.Proof;
            toProto(message: _168.Proof): Uint8Array;
            toProtoMsg(message: _168.Proof): _168.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _168.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _168.ValueOp;
            fromPartial(object: Partial<_168.ValueOp>): _168.ValueOp;
            fromAmino(object: _168.ValueOpAmino): _168.ValueOp;
            toAmino(message: _168.ValueOp): _168.ValueOpAmino;
            fromAminoMsg(object: _168.ValueOpAminoMsg): _168.ValueOp;
            fromProtoMsg(message: _168.ValueOpProtoMsg): _168.ValueOp;
            toProto(message: _168.ValueOp): Uint8Array;
            toProtoMsg(message: _168.ValueOp): _168.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _168.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _168.DominoOp;
            fromPartial(object: Partial<_168.DominoOp>): _168.DominoOp;
            fromAmino(object: _168.DominoOpAmino): _168.DominoOp;
            toAmino(message: _168.DominoOp): _168.DominoOpAmino;
            fromAminoMsg(object: _168.DominoOpAminoMsg): _168.DominoOp;
            fromProtoMsg(message: _168.DominoOpProtoMsg): _168.DominoOp;
            toProto(message: _168.DominoOp): Uint8Array;
            toProtoMsg(message: _168.DominoOp): _168.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _168.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _168.ProofOp;
            fromPartial(object: Partial<_168.ProofOp>): _168.ProofOp;
            fromAmino(object: _168.ProofOpAmino): _168.ProofOp;
            toAmino(message: _168.ProofOp): _168.ProofOpAmino;
            fromAminoMsg(object: _168.ProofOpAminoMsg): _168.ProofOp;
            fromProtoMsg(message: _168.ProofOpProtoMsg): _168.ProofOp;
            toProto(message: _168.ProofOp): Uint8Array;
            toProtoMsg(message: _168.ProofOp): _168.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _168.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _168.ProofOps;
            fromPartial(object: Partial<_168.ProofOps>): _168.ProofOps;
            fromAmino(object: _168.ProofOpsAmino): _168.ProofOps;
            toAmino(message: _168.ProofOps): _168.ProofOpsAmino;
            fromAminoMsg(object: _168.ProofOpsAminoMsg): _168.ProofOps;
            fromProtoMsg(message: _168.ProofOpsProtoMsg): _168.ProofOps;
            toProto(message: _168.ProofOps): Uint8Array;
            toProtoMsg(message: _168.ProofOps): _168.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _167.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _167.PublicKey;
            fromPartial(object: Partial<_167.PublicKey>): _167.PublicKey;
            fromAmino(object: _167.PublicKeyAmino): _167.PublicKey;
            toAmino(message: _167.PublicKey): _167.PublicKeyAmino;
            fromAminoMsg(object: _167.PublicKeyAminoMsg): _167.PublicKey;
            fromProtoMsg(message: _167.PublicKeyProtoMsg): _167.PublicKey;
            toProto(message: _167.PublicKey): Uint8Array;
            toProtoMsg(message: _167.PublicKey): _167.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _169.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: import("..").BinaryReader | Uint8Array, length?: number): _169.BitArray;
                fromPartial(object: Partial<_169.BitArray>): _169.BitArray;
                fromAmino(object: _169.BitArrayAmino): _169.BitArray;
                toAmino(message: _169.BitArray): _169.BitArrayAmino;
                fromAminoMsg(object: _169.BitArrayAminoMsg): _169.BitArray;
                fromProtoMsg(message: _169.BitArrayProtoMsg): _169.BitArray;
                toProto(message: _169.BitArray): Uint8Array;
                toProtoMsg(message: _169.BitArray): _169.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _170.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _170.NetAddress;
            fromPartial(object: Partial<_170.NetAddress>): _170.NetAddress;
            fromAmino(object: _170.NetAddressAmino): _170.NetAddress;
            toAmino(message: _170.NetAddress): _170.NetAddressAmino;
            fromAminoMsg(object: _170.NetAddressAminoMsg): _170.NetAddress;
            fromProtoMsg(message: _170.NetAddressProtoMsg): _170.NetAddress;
            toProto(message: _170.NetAddress): Uint8Array;
            toProtoMsg(message: _170.NetAddress): _170.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _170.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _170.ProtocolVersion;
            fromPartial(object: Partial<_170.ProtocolVersion>): _170.ProtocolVersion;
            fromAmino(object: _170.ProtocolVersionAmino): _170.ProtocolVersion;
            toAmino(message: _170.ProtocolVersion): _170.ProtocolVersionAmino;
            fromAminoMsg(object: _170.ProtocolVersionAminoMsg): _170.ProtocolVersion;
            fromProtoMsg(message: _170.ProtocolVersionProtoMsg): _170.ProtocolVersion;
            toProto(message: _170.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _170.ProtocolVersion): _170.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _170.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _170.DefaultNodeInfo;
            fromPartial(object: Partial<_170.DefaultNodeInfo>): _170.DefaultNodeInfo;
            fromAmino(object: _170.DefaultNodeInfoAmino): _170.DefaultNodeInfo;
            toAmino(message: _170.DefaultNodeInfo): _170.DefaultNodeInfoAmino;
            fromAminoMsg(object: _170.DefaultNodeInfoAminoMsg): _170.DefaultNodeInfo;
            fromProtoMsg(message: _170.DefaultNodeInfoProtoMsg): _170.DefaultNodeInfo;
            toProto(message: _170.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _170.DefaultNodeInfo): _170.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _170.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _170.DefaultNodeInfoOther;
            fromPartial(object: Partial<_170.DefaultNodeInfoOther>): _170.DefaultNodeInfoOther;
            fromAmino(object: _170.DefaultNodeInfoOtherAmino): _170.DefaultNodeInfoOther;
            toAmino(message: _170.DefaultNodeInfoOther): _170.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _170.DefaultNodeInfoOtherAminoMsg): _170.DefaultNodeInfoOther;
            fromProtoMsg(message: _170.DefaultNodeInfoOtherProtoMsg): _170.DefaultNodeInfoOther;
            toProto(message: _170.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _170.DefaultNodeInfoOther): _170.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _175.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _175.ValidatorSet;
            fromPartial(object: Partial<_175.ValidatorSet>): _175.ValidatorSet;
            fromAmino(object: _175.ValidatorSetAmino): _175.ValidatorSet;
            toAmino(message: _175.ValidatorSet): _175.ValidatorSetAmino;
            fromAminoMsg(object: _175.ValidatorSetAminoMsg): _175.ValidatorSet;
            fromProtoMsg(message: _175.ValidatorSetProtoMsg): _175.ValidatorSet;
            toProto(message: _175.ValidatorSet): Uint8Array;
            toProtoMsg(message: _175.ValidatorSet): _175.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _175.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _175.Validator;
            fromPartial(object: Partial<_175.Validator>): _175.Validator;
            fromAmino(object: _175.ValidatorAmino): _175.Validator;
            toAmino(message: _175.Validator): _175.ValidatorAmino;
            fromAminoMsg(object: _175.ValidatorAminoMsg): _175.Validator;
            fromProtoMsg(message: _175.ValidatorProtoMsg): _175.Validator;
            toProto(message: _175.Validator): Uint8Array;
            toProtoMsg(message: _175.Validator): _175.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _175.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _175.SimpleValidator;
            fromPartial(object: Partial<_175.SimpleValidator>): _175.SimpleValidator;
            fromAmino(object: _175.SimpleValidatorAmino): _175.SimpleValidator;
            toAmino(message: _175.SimpleValidator): _175.SimpleValidatorAmino;
            fromAminoMsg(object: _175.SimpleValidatorAminoMsg): _175.SimpleValidator;
            fromProtoMsg(message: _175.SimpleValidatorProtoMsg): _175.SimpleValidator;
            toProto(message: _175.SimpleValidator): Uint8Array;
            toProtoMsg(message: _175.SimpleValidator): _175.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _174.BlockIDFlag;
        blockIDFlagToJSON(object: _174.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _174.SignedMsgType;
        signedMsgTypeToJSON(object: _174.SignedMsgType): string;
        BlockIDFlag: typeof _174.BlockIDFlag;
        BlockIDFlagSDKType: typeof _174.BlockIDFlag;
        BlockIDFlagAmino: typeof _174.BlockIDFlag;
        SignedMsgType: typeof _174.SignedMsgType;
        SignedMsgTypeSDKType: typeof _174.SignedMsgType;
        SignedMsgTypeAmino: typeof _174.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _174.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.PartSetHeader;
            fromPartial(object: Partial<_174.PartSetHeader>): _174.PartSetHeader;
            fromAmino(object: _174.PartSetHeaderAmino): _174.PartSetHeader;
            toAmino(message: _174.PartSetHeader): _174.PartSetHeaderAmino;
            fromAminoMsg(object: _174.PartSetHeaderAminoMsg): _174.PartSetHeader;
            fromProtoMsg(message: _174.PartSetHeaderProtoMsg): _174.PartSetHeader;
            toProto(message: _174.PartSetHeader): Uint8Array;
            toProtoMsg(message: _174.PartSetHeader): _174.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _174.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Part;
            fromPartial(object: Partial<_174.Part>): _174.Part;
            fromAmino(object: _174.PartAmino): _174.Part;
            toAmino(message: _174.Part): _174.PartAmino;
            fromAminoMsg(object: _174.PartAminoMsg): _174.Part;
            fromProtoMsg(message: _174.PartProtoMsg): _174.Part;
            toProto(message: _174.Part): Uint8Array;
            toProtoMsg(message: _174.Part): _174.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _174.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.BlockID;
            fromPartial(object: Partial<_174.BlockID>): _174.BlockID;
            fromAmino(object: _174.BlockIDAmino): _174.BlockID;
            toAmino(message: _174.BlockID): _174.BlockIDAmino;
            fromAminoMsg(object: _174.BlockIDAminoMsg): _174.BlockID;
            fromProtoMsg(message: _174.BlockIDProtoMsg): _174.BlockID;
            toProto(message: _174.BlockID): Uint8Array;
            toProtoMsg(message: _174.BlockID): _174.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _174.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Header;
            fromPartial(object: Partial<_174.Header>): _174.Header;
            fromAmino(object: _174.HeaderAmino): _174.Header;
            toAmino(message: _174.Header): _174.HeaderAmino;
            fromAminoMsg(object: _174.HeaderAminoMsg): _174.Header;
            fromProtoMsg(message: _174.HeaderProtoMsg): _174.Header;
            toProto(message: _174.Header): Uint8Array;
            toProtoMsg(message: _174.Header): _174.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _174.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Data;
            fromPartial(object: Partial<_174.Data>): _174.Data;
            fromAmino(object: _174.DataAmino): _174.Data;
            toAmino(message: _174.Data): _174.DataAmino;
            fromAminoMsg(object: _174.DataAminoMsg): _174.Data;
            fromProtoMsg(message: _174.DataProtoMsg): _174.Data;
            toProto(message: _174.Data): Uint8Array;
            toProtoMsg(message: _174.Data): _174.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _174.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Vote;
            fromPartial(object: Partial<_174.Vote>): _174.Vote;
            fromAmino(object: _174.VoteAmino): _174.Vote;
            toAmino(message: _174.Vote): _174.VoteAmino;
            fromAminoMsg(object: _174.VoteAminoMsg): _174.Vote;
            fromProtoMsg(message: _174.VoteProtoMsg): _174.Vote;
            toProto(message: _174.Vote): Uint8Array;
            toProtoMsg(message: _174.Vote): _174.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _174.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Commit;
            fromPartial(object: Partial<_174.Commit>): _174.Commit;
            fromAmino(object: _174.CommitAmino): _174.Commit;
            toAmino(message: _174.Commit): _174.CommitAmino;
            fromAminoMsg(object: _174.CommitAminoMsg): _174.Commit;
            fromProtoMsg(message: _174.CommitProtoMsg): _174.Commit;
            toProto(message: _174.Commit): Uint8Array;
            toProtoMsg(message: _174.Commit): _174.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _174.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.CommitSig;
            fromPartial(object: Partial<_174.CommitSig>): _174.CommitSig;
            fromAmino(object: _174.CommitSigAmino): _174.CommitSig;
            toAmino(message: _174.CommitSig): _174.CommitSigAmino;
            fromAminoMsg(object: _174.CommitSigAminoMsg): _174.CommitSig;
            fromProtoMsg(message: _174.CommitSigProtoMsg): _174.CommitSig;
            toProto(message: _174.CommitSig): Uint8Array;
            toProtoMsg(message: _174.CommitSig): _174.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _174.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.Proposal;
            fromPartial(object: Partial<_174.Proposal>): _174.Proposal;
            fromAmino(object: _174.ProposalAmino): _174.Proposal;
            toAmino(message: _174.Proposal): _174.ProposalAmino;
            fromAminoMsg(object: _174.ProposalAminoMsg): _174.Proposal;
            fromProtoMsg(message: _174.ProposalProtoMsg): _174.Proposal;
            toProto(message: _174.Proposal): Uint8Array;
            toProtoMsg(message: _174.Proposal): _174.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _174.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.SignedHeader;
            fromPartial(object: Partial<_174.SignedHeader>): _174.SignedHeader;
            fromAmino(object: _174.SignedHeaderAmino): _174.SignedHeader;
            toAmino(message: _174.SignedHeader): _174.SignedHeaderAmino;
            fromAminoMsg(object: _174.SignedHeaderAminoMsg): _174.SignedHeader;
            fromProtoMsg(message: _174.SignedHeaderProtoMsg): _174.SignedHeader;
            toProto(message: _174.SignedHeader): Uint8Array;
            toProtoMsg(message: _174.SignedHeader): _174.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _174.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.LightBlock;
            fromPartial(object: Partial<_174.LightBlock>): _174.LightBlock;
            fromAmino(object: _174.LightBlockAmino): _174.LightBlock;
            toAmino(message: _174.LightBlock): _174.LightBlockAmino;
            fromAminoMsg(object: _174.LightBlockAminoMsg): _174.LightBlock;
            fromProtoMsg(message: _174.LightBlockProtoMsg): _174.LightBlock;
            toProto(message: _174.LightBlock): Uint8Array;
            toProtoMsg(message: _174.LightBlock): _174.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _174.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.BlockMeta;
            fromPartial(object: Partial<_174.BlockMeta>): _174.BlockMeta;
            fromAmino(object: _174.BlockMetaAmino): _174.BlockMeta;
            toAmino(message: _174.BlockMeta): _174.BlockMetaAmino;
            fromAminoMsg(object: _174.BlockMetaAminoMsg): _174.BlockMeta;
            fromProtoMsg(message: _174.BlockMetaProtoMsg): _174.BlockMeta;
            toProto(message: _174.BlockMeta): Uint8Array;
            toProtoMsg(message: _174.BlockMeta): _174.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _174.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _174.TxProof;
            fromPartial(object: Partial<_174.TxProof>): _174.TxProof;
            fromAmino(object: _174.TxProofAmino): _174.TxProof;
            toAmino(message: _174.TxProof): _174.TxProofAmino;
            fromAminoMsg(object: _174.TxProofAminoMsg): _174.TxProof;
            fromProtoMsg(message: _174.TxProofProtoMsg): _174.TxProof;
            toProto(message: _174.TxProof): Uint8Array;
            toProtoMsg(message: _174.TxProof): _174.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _173.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.ConsensusParams;
            fromPartial(object: Partial<_173.ConsensusParams>): _173.ConsensusParams;
            fromAmino(object: _173.ConsensusParamsAmino): _173.ConsensusParams;
            toAmino(message: _173.ConsensusParams): _173.ConsensusParamsAmino;
            fromAminoMsg(object: _173.ConsensusParamsAminoMsg): _173.ConsensusParams;
            fromProtoMsg(message: _173.ConsensusParamsProtoMsg): _173.ConsensusParams;
            toProto(message: _173.ConsensusParams): Uint8Array;
            toProtoMsg(message: _173.ConsensusParams): _173.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _173.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.BlockParams;
            fromPartial(object: Partial<_173.BlockParams>): _173.BlockParams;
            fromAmino(object: _173.BlockParamsAmino): _173.BlockParams;
            toAmino(message: _173.BlockParams): _173.BlockParamsAmino;
            fromAminoMsg(object: _173.BlockParamsAminoMsg): _173.BlockParams;
            fromProtoMsg(message: _173.BlockParamsProtoMsg): _173.BlockParams;
            toProto(message: _173.BlockParams): Uint8Array;
            toProtoMsg(message: _173.BlockParams): _173.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _173.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.EvidenceParams;
            fromPartial(object: Partial<_173.EvidenceParams>): _173.EvidenceParams;
            fromAmino(object: _173.EvidenceParamsAmino): _173.EvidenceParams;
            toAmino(message: _173.EvidenceParams): _173.EvidenceParamsAmino;
            fromAminoMsg(object: _173.EvidenceParamsAminoMsg): _173.EvidenceParams;
            fromProtoMsg(message: _173.EvidenceParamsProtoMsg): _173.EvidenceParams;
            toProto(message: _173.EvidenceParams): Uint8Array;
            toProtoMsg(message: _173.EvidenceParams): _173.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _173.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.ValidatorParams;
            fromPartial(object: Partial<_173.ValidatorParams>): _173.ValidatorParams;
            fromAmino(object: _173.ValidatorParamsAmino): _173.ValidatorParams;
            toAmino(message: _173.ValidatorParams): _173.ValidatorParamsAmino;
            fromAminoMsg(object: _173.ValidatorParamsAminoMsg): _173.ValidatorParams;
            fromProtoMsg(message: _173.ValidatorParamsProtoMsg): _173.ValidatorParams;
            toProto(message: _173.ValidatorParams): Uint8Array;
            toProtoMsg(message: _173.ValidatorParams): _173.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _173.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.VersionParams;
            fromPartial(object: Partial<_173.VersionParams>): _173.VersionParams;
            fromAmino(object: _173.VersionParamsAmino): _173.VersionParams;
            toAmino(message: _173.VersionParams): _173.VersionParamsAmino;
            fromAminoMsg(object: _173.VersionParamsAminoMsg): _173.VersionParams;
            fromProtoMsg(message: _173.VersionParamsProtoMsg): _173.VersionParams;
            toProto(message: _173.VersionParams): Uint8Array;
            toProtoMsg(message: _173.VersionParams): _173.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _173.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _173.HashedParams;
            fromPartial(object: Partial<_173.HashedParams>): _173.HashedParams;
            fromAmino(object: _173.HashedParamsAmino): _173.HashedParams;
            toAmino(message: _173.HashedParams): _173.HashedParamsAmino;
            fromAminoMsg(object: _173.HashedParamsAminoMsg): _173.HashedParams;
            fromProtoMsg(message: _173.HashedParamsProtoMsg): _173.HashedParams;
            toProto(message: _173.HashedParams): Uint8Array;
            toProtoMsg(message: _173.HashedParams): _173.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _172.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _172.Evidence;
            fromPartial(object: Partial<_172.Evidence>): _172.Evidence;
            fromAmino(object: _172.EvidenceAmino): _172.Evidence;
            toAmino(message: _172.Evidence): _172.EvidenceAmino;
            fromAminoMsg(object: _172.EvidenceAminoMsg): _172.Evidence;
            fromProtoMsg(message: _172.EvidenceProtoMsg): _172.Evidence;
            toProto(message: _172.Evidence): Uint8Array;
            toProtoMsg(message: _172.Evidence): _172.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _172.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _172.DuplicateVoteEvidence;
            fromPartial(object: Partial<_172.DuplicateVoteEvidence>): _172.DuplicateVoteEvidence;
            fromAmino(object: _172.DuplicateVoteEvidenceAmino): _172.DuplicateVoteEvidence;
            toAmino(message: _172.DuplicateVoteEvidence): _172.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _172.DuplicateVoteEvidenceAminoMsg): _172.DuplicateVoteEvidence;
            fromProtoMsg(message: _172.DuplicateVoteEvidenceProtoMsg): _172.DuplicateVoteEvidence;
            toProto(message: _172.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _172.DuplicateVoteEvidence): _172.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _172.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _172.LightClientAttackEvidence;
            fromPartial(object: Partial<_172.LightClientAttackEvidence>): _172.LightClientAttackEvidence;
            fromAmino(object: _172.LightClientAttackEvidenceAmino): _172.LightClientAttackEvidence;
            toAmino(message: _172.LightClientAttackEvidence): _172.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _172.LightClientAttackEvidenceAminoMsg): _172.LightClientAttackEvidence;
            fromProtoMsg(message: _172.LightClientAttackEvidenceProtoMsg): _172.LightClientAttackEvidence;
            toProto(message: _172.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _172.LightClientAttackEvidence): _172.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _172.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _172.EvidenceList;
            fromPartial(object: Partial<_172.EvidenceList>): _172.EvidenceList;
            fromAmino(object: _172.EvidenceListAmino): _172.EvidenceList;
            toAmino(message: _172.EvidenceList): _172.EvidenceListAmino;
            fromAminoMsg(object: _172.EvidenceListAminoMsg): _172.EvidenceList;
            fromProtoMsg(message: _172.EvidenceListProtoMsg): _172.EvidenceList;
            toProto(message: _172.EvidenceList): Uint8Array;
            toProtoMsg(message: _172.EvidenceList): _172.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _171.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _171.Block;
            fromPartial(object: Partial<_171.Block>): _171.Block;
            fromAmino(object: _171.BlockAmino): _171.Block;
            toAmino(message: _171.Block): _171.BlockAmino;
            fromAminoMsg(object: _171.BlockAminoMsg): _171.Block;
            fromProtoMsg(message: _171.BlockProtoMsg): _171.Block;
            toProto(message: _171.Block): Uint8Array;
            toProtoMsg(message: _171.Block): _171.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _176.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _176.App;
            fromPartial(object: Partial<_176.App>): _176.App;
            fromAmino(object: _176.AppAmino): _176.App;
            toAmino(message: _176.App): _176.AppAmino;
            fromAminoMsg(object: _176.AppAminoMsg): _176.App;
            fromProtoMsg(message: _176.AppProtoMsg): _176.App;
            toProto(message: _176.App): Uint8Array;
            toProtoMsg(message: _176.App): _176.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _176.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _176.Consensus;
            fromPartial(object: Partial<_176.Consensus>): _176.Consensus;
            fromAmino(object: _176.ConsensusAmino): _176.Consensus;
            toAmino(message: _176.Consensus): _176.ConsensusAmino;
            fromAminoMsg(object: _176.ConsensusAminoMsg): _176.Consensus;
            fromProtoMsg(message: _176.ConsensusProtoMsg): _176.Consensus;
            toProto(message: _176.Consensus): Uint8Array;
            toProtoMsg(message: _176.Consensus): _176.ConsensusProtoMsg;
        };
    };
}
