import * as _160 from "./api/http";
import * as _161 from "./api/httpbody";
import * as _162 from "./protobuf/any";
import * as _163 from "./protobuf/timestamp";
import * as _164 from "./protobuf/duration";
import * as _165 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _161.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _161.HttpBody;
            fromPartial(object: Partial<_161.HttpBody>): _161.HttpBody;
            fromAmino(object: _161.HttpBodyAmino): _161.HttpBody;
            toAmino(message: _161.HttpBody): _161.HttpBodyAmino;
            fromAminoMsg(object: _161.HttpBodyAminoMsg): _161.HttpBody;
            fromProtoMsg(message: _161.HttpBodyProtoMsg): _161.HttpBody;
            toProto(message: _161.HttpBody): Uint8Array;
            toProtoMsg(message: _161.HttpBody): _161.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _160.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _160.Http;
            fromPartial(object: Partial<_160.Http>): _160.Http;
            fromAmino(object: _160.HttpAmino): _160.Http;
            toAmino(message: _160.Http): _160.HttpAmino;
            fromAminoMsg(object: _160.HttpAminoMsg): _160.Http;
            fromProtoMsg(message: _160.HttpProtoMsg): _160.Http;
            toProto(message: _160.Http): Uint8Array;
            toProtoMsg(message: _160.Http): _160.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _160.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _160.HttpRule;
            fromPartial(object: Partial<_160.HttpRule>): _160.HttpRule;
            fromAmino(object: _160.HttpRuleAmino): _160.HttpRule;
            toAmino(message: _160.HttpRule): _160.HttpRuleAmino;
            fromAminoMsg(object: _160.HttpRuleAminoMsg): _160.HttpRule;
            fromProtoMsg(message: _160.HttpRuleProtoMsg): _160.HttpRule;
            toProto(message: _160.HttpRule): Uint8Array;
            toProtoMsg(message: _160.HttpRule): _160.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _160.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _160.CustomHttpPattern;
            fromPartial(object: Partial<_160.CustomHttpPattern>): _160.CustomHttpPattern;
            fromAmino(object: _160.CustomHttpPatternAmino): _160.CustomHttpPattern;
            toAmino(message: _160.CustomHttpPattern): _160.CustomHttpPatternAmino;
            fromAminoMsg(object: _160.CustomHttpPatternAminoMsg): _160.CustomHttpPattern;
            fromProtoMsg(message: _160.CustomHttpPatternProtoMsg): _160.CustomHttpPattern;
            toProto(message: _160.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _160.CustomHttpPattern): _160.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _165.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _165.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _165.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _165.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _165.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _165.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _165.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _165.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _165.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _165.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _165.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _165.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _165.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _165.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _165.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _165.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _165.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _165.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _165.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _165.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _165.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _165.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _165.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _165.FieldOptions_CType;
        FieldOptions_JSType: typeof _165.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _165.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _165.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _165.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _165.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _165.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _165.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.FileDescriptorSet;
            fromPartial(object: Partial<_165.FileDescriptorSet>): _165.FileDescriptorSet;
            fromAmino(object: _165.FileDescriptorSetAmino): _165.FileDescriptorSet;
            toAmino(message: _165.FileDescriptorSet): _165.FileDescriptorSetAmino;
            fromAminoMsg(object: _165.FileDescriptorSetAminoMsg): _165.FileDescriptorSet;
            fromProtoMsg(message: _165.FileDescriptorSetProtoMsg): _165.FileDescriptorSet;
            toProto(message: _165.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _165.FileDescriptorSet): _165.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _165.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.FileDescriptorProto;
            fromPartial(object: Partial<_165.FileDescriptorProto>): _165.FileDescriptorProto;
            fromAmino(object: _165.FileDescriptorProtoAmino): _165.FileDescriptorProto;
            toAmino(message: _165.FileDescriptorProto): _165.FileDescriptorProtoAmino;
            fromAminoMsg(object: _165.FileDescriptorProtoAminoMsg): _165.FileDescriptorProto;
            fromProtoMsg(message: _165.FileDescriptorProtoProtoMsg): _165.FileDescriptorProto;
            toProto(message: _165.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.FileDescriptorProto): _165.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _165.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.DescriptorProto;
            fromPartial(object: Partial<_165.DescriptorProto>): _165.DescriptorProto;
            fromAmino(object: _165.DescriptorProtoAmino): _165.DescriptorProto;
            toAmino(message: _165.DescriptorProto): _165.DescriptorProtoAmino;
            fromAminoMsg(object: _165.DescriptorProtoAminoMsg): _165.DescriptorProto;
            fromProtoMsg(message: _165.DescriptorProtoProtoMsg): _165.DescriptorProto;
            toProto(message: _165.DescriptorProto): Uint8Array;
            toProtoMsg(message: _165.DescriptorProto): _165.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _165.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_165.DescriptorProto_ExtensionRange>): _165.DescriptorProto_ExtensionRange;
            fromAmino(object: _165.DescriptorProto_ExtensionRangeAmino): _165.DescriptorProto_ExtensionRange;
            toAmino(message: _165.DescriptorProto_ExtensionRange): _165.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _165.DescriptorProto_ExtensionRangeAminoMsg): _165.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _165.DescriptorProto_ExtensionRangeProtoMsg): _165.DescriptorProto_ExtensionRange;
            toProto(message: _165.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _165.DescriptorProto_ExtensionRange): _165.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _165.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_165.DescriptorProto_ReservedRange>): _165.DescriptorProto_ReservedRange;
            fromAmino(object: _165.DescriptorProto_ReservedRangeAmino): _165.DescriptorProto_ReservedRange;
            toAmino(message: _165.DescriptorProto_ReservedRange): _165.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _165.DescriptorProto_ReservedRangeAminoMsg): _165.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _165.DescriptorProto_ReservedRangeProtoMsg): _165.DescriptorProto_ReservedRange;
            toProto(message: _165.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _165.DescriptorProto_ReservedRange): _165.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _165.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.ExtensionRangeOptions;
            fromPartial(object: Partial<_165.ExtensionRangeOptions>): _165.ExtensionRangeOptions;
            fromAmino(object: _165.ExtensionRangeOptionsAmino): _165.ExtensionRangeOptions;
            toAmino(message: _165.ExtensionRangeOptions): _165.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _165.ExtensionRangeOptionsAminoMsg): _165.ExtensionRangeOptions;
            fromProtoMsg(message: _165.ExtensionRangeOptionsProtoMsg): _165.ExtensionRangeOptions;
            toProto(message: _165.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _165.ExtensionRangeOptions): _165.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _165.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.FieldDescriptorProto;
            fromPartial(object: Partial<_165.FieldDescriptorProto>): _165.FieldDescriptorProto;
            fromAmino(object: _165.FieldDescriptorProtoAmino): _165.FieldDescriptorProto;
            toAmino(message: _165.FieldDescriptorProto): _165.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _165.FieldDescriptorProtoAminoMsg): _165.FieldDescriptorProto;
            fromProtoMsg(message: _165.FieldDescriptorProtoProtoMsg): _165.FieldDescriptorProto;
            toProto(message: _165.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.FieldDescriptorProto): _165.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _165.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.OneofDescriptorProto;
            fromPartial(object: Partial<_165.OneofDescriptorProto>): _165.OneofDescriptorProto;
            fromAmino(object: _165.OneofDescriptorProtoAmino): _165.OneofDescriptorProto;
            toAmino(message: _165.OneofDescriptorProto): _165.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _165.OneofDescriptorProtoAminoMsg): _165.OneofDescriptorProto;
            fromProtoMsg(message: _165.OneofDescriptorProtoProtoMsg): _165.OneofDescriptorProto;
            toProto(message: _165.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.OneofDescriptorProto): _165.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _165.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.EnumDescriptorProto;
            fromPartial(object: Partial<_165.EnumDescriptorProto>): _165.EnumDescriptorProto;
            fromAmino(object: _165.EnumDescriptorProtoAmino): _165.EnumDescriptorProto;
            toAmino(message: _165.EnumDescriptorProto): _165.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _165.EnumDescriptorProtoAminoMsg): _165.EnumDescriptorProto;
            fromProtoMsg(message: _165.EnumDescriptorProtoProtoMsg): _165.EnumDescriptorProto;
            toProto(message: _165.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.EnumDescriptorProto): _165.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _165.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_165.EnumDescriptorProto_EnumReservedRange>): _165.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _165.EnumDescriptorProto_EnumReservedRangeAmino): _165.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _165.EnumDescriptorProto_EnumReservedRange): _165.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _165.EnumDescriptorProto_EnumReservedRangeAminoMsg): _165.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _165.EnumDescriptorProto_EnumReservedRangeProtoMsg): _165.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _165.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _165.EnumDescriptorProto_EnumReservedRange): _165.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _165.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.EnumValueDescriptorProto;
            fromPartial(object: Partial<_165.EnumValueDescriptorProto>): _165.EnumValueDescriptorProto;
            fromAmino(object: _165.EnumValueDescriptorProtoAmino): _165.EnumValueDescriptorProto;
            toAmino(message: _165.EnumValueDescriptorProto): _165.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _165.EnumValueDescriptorProtoAminoMsg): _165.EnumValueDescriptorProto;
            fromProtoMsg(message: _165.EnumValueDescriptorProtoProtoMsg): _165.EnumValueDescriptorProto;
            toProto(message: _165.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.EnumValueDescriptorProto): _165.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _165.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.ServiceDescriptorProto;
            fromPartial(object: Partial<_165.ServiceDescriptorProto>): _165.ServiceDescriptorProto;
            fromAmino(object: _165.ServiceDescriptorProtoAmino): _165.ServiceDescriptorProto;
            toAmino(message: _165.ServiceDescriptorProto): _165.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _165.ServiceDescriptorProtoAminoMsg): _165.ServiceDescriptorProto;
            fromProtoMsg(message: _165.ServiceDescriptorProtoProtoMsg): _165.ServiceDescriptorProto;
            toProto(message: _165.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.ServiceDescriptorProto): _165.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _165.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.MethodDescriptorProto;
            fromPartial(object: Partial<_165.MethodDescriptorProto>): _165.MethodDescriptorProto;
            fromAmino(object: _165.MethodDescriptorProtoAmino): _165.MethodDescriptorProto;
            toAmino(message: _165.MethodDescriptorProto): _165.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _165.MethodDescriptorProtoAminoMsg): _165.MethodDescriptorProto;
            fromProtoMsg(message: _165.MethodDescriptorProtoProtoMsg): _165.MethodDescriptorProto;
            toProto(message: _165.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _165.MethodDescriptorProto): _165.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _165.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.FileOptions;
            fromPartial(object: Partial<_165.FileOptions>): _165.FileOptions;
            fromAmino(object: _165.FileOptionsAmino): _165.FileOptions;
            toAmino(message: _165.FileOptions): _165.FileOptionsAmino;
            fromAminoMsg(object: _165.FileOptionsAminoMsg): _165.FileOptions;
            fromProtoMsg(message: _165.FileOptionsProtoMsg): _165.FileOptions;
            toProto(message: _165.FileOptions): Uint8Array;
            toProtoMsg(message: _165.FileOptions): _165.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _165.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.MessageOptions;
            fromPartial(object: Partial<_165.MessageOptions>): _165.MessageOptions;
            fromAmino(object: _165.MessageOptionsAmino): _165.MessageOptions;
            toAmino(message: _165.MessageOptions): _165.MessageOptionsAmino;
            fromAminoMsg(object: _165.MessageOptionsAminoMsg): _165.MessageOptions;
            fromProtoMsg(message: _165.MessageOptionsProtoMsg): _165.MessageOptions;
            toProto(message: _165.MessageOptions): Uint8Array;
            toProtoMsg(message: _165.MessageOptions): _165.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _165.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.FieldOptions;
            fromPartial(object: Partial<_165.FieldOptions>): _165.FieldOptions;
            fromAmino(object: _165.FieldOptionsAmino): _165.FieldOptions;
            toAmino(message: _165.FieldOptions): _165.FieldOptionsAmino;
            fromAminoMsg(object: _165.FieldOptionsAminoMsg): _165.FieldOptions;
            fromProtoMsg(message: _165.FieldOptionsProtoMsg): _165.FieldOptions;
            toProto(message: _165.FieldOptions): Uint8Array;
            toProtoMsg(message: _165.FieldOptions): _165.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _165.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.OneofOptions;
            fromPartial(object: Partial<_165.OneofOptions>): _165.OneofOptions;
            fromAmino(object: _165.OneofOptionsAmino): _165.OneofOptions;
            toAmino(message: _165.OneofOptions): _165.OneofOptionsAmino;
            fromAminoMsg(object: _165.OneofOptionsAminoMsg): _165.OneofOptions;
            fromProtoMsg(message: _165.OneofOptionsProtoMsg): _165.OneofOptions;
            toProto(message: _165.OneofOptions): Uint8Array;
            toProtoMsg(message: _165.OneofOptions): _165.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _165.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.EnumOptions;
            fromPartial(object: Partial<_165.EnumOptions>): _165.EnumOptions;
            fromAmino(object: _165.EnumOptionsAmino): _165.EnumOptions;
            toAmino(message: _165.EnumOptions): _165.EnumOptionsAmino;
            fromAminoMsg(object: _165.EnumOptionsAminoMsg): _165.EnumOptions;
            fromProtoMsg(message: _165.EnumOptionsProtoMsg): _165.EnumOptions;
            toProto(message: _165.EnumOptions): Uint8Array;
            toProtoMsg(message: _165.EnumOptions): _165.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _165.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.EnumValueOptions;
            fromPartial(object: Partial<_165.EnumValueOptions>): _165.EnumValueOptions;
            fromAmino(object: _165.EnumValueOptionsAmino): _165.EnumValueOptions;
            toAmino(message: _165.EnumValueOptions): _165.EnumValueOptionsAmino;
            fromAminoMsg(object: _165.EnumValueOptionsAminoMsg): _165.EnumValueOptions;
            fromProtoMsg(message: _165.EnumValueOptionsProtoMsg): _165.EnumValueOptions;
            toProto(message: _165.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _165.EnumValueOptions): _165.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _165.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.ServiceOptions;
            fromPartial(object: Partial<_165.ServiceOptions>): _165.ServiceOptions;
            fromAmino(object: _165.ServiceOptionsAmino): _165.ServiceOptions;
            toAmino(message: _165.ServiceOptions): _165.ServiceOptionsAmino;
            fromAminoMsg(object: _165.ServiceOptionsAminoMsg): _165.ServiceOptions;
            fromProtoMsg(message: _165.ServiceOptionsProtoMsg): _165.ServiceOptions;
            toProto(message: _165.ServiceOptions): Uint8Array;
            toProtoMsg(message: _165.ServiceOptions): _165.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _165.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.MethodOptions;
            fromPartial(object: Partial<_165.MethodOptions>): _165.MethodOptions;
            fromAmino(object: _165.MethodOptionsAmino): _165.MethodOptions;
            toAmino(message: _165.MethodOptions): _165.MethodOptionsAmino;
            fromAminoMsg(object: _165.MethodOptionsAminoMsg): _165.MethodOptions;
            fromProtoMsg(message: _165.MethodOptionsProtoMsg): _165.MethodOptions;
            toProto(message: _165.MethodOptions): Uint8Array;
            toProtoMsg(message: _165.MethodOptions): _165.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _165.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.UninterpretedOption;
            fromPartial(object: Partial<_165.UninterpretedOption>): _165.UninterpretedOption;
            fromAmino(object: _165.UninterpretedOptionAmino): _165.UninterpretedOption;
            toAmino(message: _165.UninterpretedOption): _165.UninterpretedOptionAmino;
            fromAminoMsg(object: _165.UninterpretedOptionAminoMsg): _165.UninterpretedOption;
            fromProtoMsg(message: _165.UninterpretedOptionProtoMsg): _165.UninterpretedOption;
            toProto(message: _165.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _165.UninterpretedOption): _165.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _165.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_165.UninterpretedOption_NamePart>): _165.UninterpretedOption_NamePart;
            fromAmino(object: _165.UninterpretedOption_NamePartAmino): _165.UninterpretedOption_NamePart;
            toAmino(message: _165.UninterpretedOption_NamePart): _165.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _165.UninterpretedOption_NamePartAminoMsg): _165.UninterpretedOption_NamePart;
            fromProtoMsg(message: _165.UninterpretedOption_NamePartProtoMsg): _165.UninterpretedOption_NamePart;
            toProto(message: _165.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _165.UninterpretedOption_NamePart): _165.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _165.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.SourceCodeInfo;
            fromPartial(object: Partial<_165.SourceCodeInfo>): _165.SourceCodeInfo;
            fromAmino(object: _165.SourceCodeInfoAmino): _165.SourceCodeInfo;
            toAmino(message: _165.SourceCodeInfo): _165.SourceCodeInfoAmino;
            fromAminoMsg(object: _165.SourceCodeInfoAminoMsg): _165.SourceCodeInfo;
            fromProtoMsg(message: _165.SourceCodeInfoProtoMsg): _165.SourceCodeInfo;
            toProto(message: _165.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _165.SourceCodeInfo): _165.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _165.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.SourceCodeInfo_Location;
            fromPartial(object: Partial<_165.SourceCodeInfo_Location>): _165.SourceCodeInfo_Location;
            fromAmino(object: _165.SourceCodeInfo_LocationAmino): _165.SourceCodeInfo_Location;
            toAmino(message: _165.SourceCodeInfo_Location): _165.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _165.SourceCodeInfo_LocationAminoMsg): _165.SourceCodeInfo_Location;
            fromProtoMsg(message: _165.SourceCodeInfo_LocationProtoMsg): _165.SourceCodeInfo_Location;
            toProto(message: _165.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _165.SourceCodeInfo_Location): _165.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _165.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.GeneratedCodeInfo;
            fromPartial(object: Partial<_165.GeneratedCodeInfo>): _165.GeneratedCodeInfo;
            fromAmino(object: _165.GeneratedCodeInfoAmino): _165.GeneratedCodeInfo;
            toAmino(message: _165.GeneratedCodeInfo): _165.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _165.GeneratedCodeInfoAminoMsg): _165.GeneratedCodeInfo;
            fromProtoMsg(message: _165.GeneratedCodeInfoProtoMsg): _165.GeneratedCodeInfo;
            toProto(message: _165.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _165.GeneratedCodeInfo): _165.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _165.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _165.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_165.GeneratedCodeInfo_Annotation>): _165.GeneratedCodeInfo_Annotation;
            fromAmino(object: _165.GeneratedCodeInfo_AnnotationAmino): _165.GeneratedCodeInfo_Annotation;
            toAmino(message: _165.GeneratedCodeInfo_Annotation): _165.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _165.GeneratedCodeInfo_AnnotationAminoMsg): _165.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _165.GeneratedCodeInfo_AnnotationProtoMsg): _165.GeneratedCodeInfo_Annotation;
            toProto(message: _165.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _165.GeneratedCodeInfo_Annotation): _165.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _164.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _164.Duration;
            fromPartial(object: Partial<_164.Duration>): _164.Duration;
            fromAmino(object: _164.DurationAmino): _164.Duration;
            toAmino(message: _164.Duration): _164.DurationAmino;
            fromAminoMsg(object: _164.DurationAminoMsg): _164.Duration;
            fromProtoMsg(message: _164.DurationProtoMsg): _164.Duration;
            toProto(message: _164.Duration): Uint8Array;
            toProtoMsg(message: _164.Duration): _164.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _163.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _163.Timestamp;
            fromPartial(object: Partial<_163.Timestamp>): _163.Timestamp;
            fromAmino(object: _163.TimestampAmino): _163.Timestamp;
            toAmino(message: _163.Timestamp): _163.TimestampAmino;
            fromAminoMsg(object: _163.TimestampAminoMsg): _163.Timestamp;
            fromProtoMsg(message: _163.TimestampProtoMsg): _163.Timestamp;
            toProto(message: _163.Timestamp): Uint8Array;
            toProtoMsg(message: _163.Timestamp): _163.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _162.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _162.Any;
            fromPartial(object: Partial<_162.Any>): _162.Any;
            fromAmino(object: _162.AnyAmino): _162.Any;
            toAmino(message: _162.Any): _162.AnyAmino;
            fromAminoMsg(object: _162.AnyAminoMsg): _162.Any;
            fromProtoMsg(message: _162.AnyProtoMsg): _162.Any;
            toProto(message: _162.Any): Uint8Array;
            toProtoMsg(message: _162.Any): _162.AnyProtoMsg;
        };
    };
}
